name: Node CI First Test

on: [push]

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - name: yarn install, build, and test
      container:
        image: node:10.16-jessie
      run: |
        yarn run build
        yarn test
      env:
        CI: true

  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
