name: Node CI First Test

on: [push]

jobs:
  name: Hello World
  description: Greet someone and record the time
  inputs:
    who-to-greet:  # id of input
      description: Who to greet
      required: true
      default: World
  outputs:
    time: # id of output
      description: The time we greeted you
  runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.who-to-greet }}
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
